### ISSUE TITLE
[fix]: keep original format of string before and after map-get(...)

### ISSUE THREAD

**Issue by marcalexiei** [Scrum/postcss-map-get#10]
Thank you for the plugin. While using it I have the following issue:

**INPUT**
```css
.foo {
    border: 1px solid map-get((borderColor: #FFF), borderColor);
}
```

**ACTUAL**
```css
.foo {
    border: 1pxsolid#FFF;
}
```

**EXPECTED**
```css
.foo {
    border: 1px solid #FFF;
}
```

## Code
```javascript
var postcss = require('postcss');
var mapGet = require('postcss-map-get');
 
// CSS to be processed
var css = `
.foo {
    border: 1px solid map-get((borderColor: #FFF), borderColor);
}
`;
 
// Process CSS
var output = postcss()
  .use(mapGet())
  .process(css)
  .css;
 
console.log('result:', output);
```

[Example on runkit](https://runkit.com/embed/zt75xp8pcirp)
